services:
  openai:
    container_name: "openai"
    image: 'openai:latest'
    build: 
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:3030:3030"
    depends_on:
      - postgres-db
    environment:
      # TODO: Define firestore URL
      FIRESTORE_DB_URL: ""
      OPENAI_API_KEY: ""
      IPFLARE_API_KEY: "d4815a7185da6aae.69f941c643a3f41f751fcc9ef59dcfcfed08a00fb57907b4e750a4a1cdbffc3a"
      POSTGRES_URL: "postgres://postgres:password@postgres-db:5432/postgres?sslmode=disable"
    networks:
      - backend

  postgres-db:
    image: 'postgres:latest'
    restart: always
    container_name: "postgres-emulator"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    command: ["-c", "ssl=off"]
    networks:
      - backend

networks:
  backend:
    driver: bridge