services:
  openai:
    container_name: "openai"
    image: 'openai:latest'
    volumes:
      # NOTE: ${HOME} is not expanded to the home directory on the host machine, 
      # NOTE: docker inspect <service_name> is used to display mounts  
      # sudo docker inspect <service> -f 'json' output.json
      # TODO: We should find a more generalized way of specifying 
      # the path to credentials.
      - /home/alexey/.config/gcloud:/gcloud/:ro
    build: 
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:3030:3030"
    depends_on:
      - postgres-db
    env_file:
      - ".env"
    networks:
      - backend

  postgres-db:
    image: 'postgres:latest'
    restart: always
    container_name: "postgres-emulator"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    command: ["-c", "ssl=off"]
    networks:
      - backend

networks:
  backend:
    driver: bridge
